The rust 1.45.0 build fails with
```
    Updating crates.io index
error: failed to get `serde` as a dependency of package `url v2.2.2 (/home/icecold/workspace/rust-url/url)`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  error reading from the zlib stream; class=Zlib (5)
```

Fixed by `CARGO_NET_GIT_FETCH_WITH_CLI=true cargo build --all-targets`
According to https://github.com/rust-lang/cargo/issues/10303